### ISSUE TITLE
Is there an ios version or windows version?

### ISSUE THREAD

**Issue by HeppleX** [YuAmbrose/Free-SSR-Shadowsocks#1]

**Comment by YuAmbrose** [comment]
No, not currently. However, you can export nodes in Android devices to use in ios, mac, and window.

**Comment by YuAmbrose** [comment]
> _No description provided._

No, not currently. However, you can export nodes in Android devices to use in ios, mac, and window.

**Comment by HeppleX** [comment]
I don't have an Android device, lol.
